### ISSUE TITLE
Result file is empty

### ISSUE THREAD

**Issue by yuzhenpeng** [sciseim/RadAA#1]
Dear Seim，

Thanks for your very useful tool. Now I am confused. If the output is empty, does it mean no amino acid sites were found? Why the two amino acid sites are the same, and the results are still empty？
![image](https://user-images.githubusercontent.com/31943277/54827186-61e68180-4cec-11e9-8214-012415a8fe45.png)

I look forward to your help. Thank you, sir.
Zhenpeng

**Comment by sciseim** [comment]
hi Zhenpeng,

The tool will only output a result if there is a change according to specific rules (see the manuscript). In this case, a P and L are in the same 'group', so it is not considered a radical amino acid change.

all the best,
Inge

**Comment by sciseim** [comment]
Found an old Perl script which will do what you want:
[uniqueAAmany.zip](https://github.com/sciseim/RadAA/files/3088119/uniqueAAmany.zip)


To use, type:
_uniqueAAv2.pl [filename] [referencespecies # in MSA] [target # in MSA]__

so e.g.
if reference species is Macropus_eugenii above (species 1) and species 19 and 20 are your targets:
_perl ./uniqueAAv2.pl example.fa 1 19 20_


Have not tested the script for more than six years: let me know if it is broken

**Comment by yuzhenpeng** [comment]
Dear professor,

Thanks for your kind help.
By read the manuscript, now I have understood the use of RadAA.

Best wishes.

Zhenpeng

**Comment by sciseim** [comment]
no problem.

**Comment by yuzhenpeng** [comment]
Dear Inge,

I have 81 genes associated with sleep which contain 30 mammals, such as Primates, Carnivora, Cetartiodactyla and Afrotheria. As we know, whales have obviouslly different sleep model that refer to half of the brain stays asleep and the other half is awake. So I want to know whether the genes associated with sleep occur the convergent evolution between whales.

Now I had prepare the gene list of protein sequence after alignment and sort each sequence by name used the FASTAheadernumber.
![image](https://user-images.githubusercontent.com/31943277/70844385-51c69180-1e7b-11ea-823b-6151a49463b2.png)
 As shown above, every gene follow this order. So, number 2 8 11 15 16 19 21 23 28 which are my interest in. Next I used the follow command for identifing the convergent sites between all whals.
```
for i in *.fas;do
RadAA -i $i 2 8 11 15 16 19 21 23 28
done
```
But, the result file without anything.And, when I do this by eye, I can found some sites. Like ADCY3 gene 214, 616 and 839 sites. I don't know the reason.
![image](https://user-images.githubusercontent.com/31943277/70845372-cbb14780-1e88-11ea-9391-a39ecd086b85.png)

Look forward to your help. 
Thank you. 

Zhenpeng

**Comment by sciseim** [comment]
Issue should not be resolved. Appears to have been due to Perl not interpreting ') {' if on a new line (that is, not directly adjacent to a variable).
